openapi: "3.0.0"
info:
  description: "BEV Transformator - Das Koordinatentransformationsservice des Bundesamts für Eich- und Vermessungswesens"
  version: "3.0"
  title: "BEV Transformator"
  termsOfService: "http://www.bev.gv.at"
  contact:
    email: "marketing@bev.gv.at"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "https://transformator.bev.gv.at/at.gv.bev.transformator/api/v3.0"
    description: "Transformationsserver"
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
          

tags:
- name: "advanced"
  description: "Komplexe Transformation einfach"
  
- name: "cadastre"
  description: "Anschluss ans Festpunktfeld mit Passpunkten"
  
- name: "helmert"
  description: "Helmert Transformation/Determination 2D/3D"
  
- name: "austrian"
  description: "ETRS <-> MGI"
  
- name: "datetime"
  description: "Umrechnung verschiedener Datumsformate."

- name: "height"
  description: "MicroService für Höhenberechnung"


paths:

  /height/singleHeight/:
    get:
      servers:
        - url: "https://transformator.bev.gv.at/at.gv.bev.transformator/api/"
      tags:
      - "height"
      summary: "Abfrage einer Gebrauchshöhe eines SinglePoints in WGS84"
      parameters:
        - in: query
          name: point
          schema:
            type: string
          required: true
          description: "Übergabe von phi und lambda als float"
          example: 15.09,48.13
      responses:
        200:
          description: "erfolgreiche Höhenbestimmung"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/singleHeight"
        400:
          description: "Fehlerhafte Parameterübergabe"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: "string"
                example:
                  message: "'phi' wurde nicht richtig übergeben"


  /height/heightProfile/:
    post:
      servers:
        - url: "https://transformator.bev.gv.at/at.gv.bev.transformator/api/"
      tags:
        - "height"
      summary: "Höhenprofil an den StepPoints"
      description: "Berechnen des Höhenprofil an 'steps' x äquidistanten Zwischenpunkten entlang des übergebenen Linestrings (point_list). Es können maximal 500 Höhenwerte berechnet werden. Wird steps>500 übergeben, wird automatisch steps=500 gesetzt."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/heightProfileRequest"
      responses:
        200:
          description: "Berechnung erfolgreich"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/heightProfile"
        400:
          description: "Fehlerhaft Parameterübergabe"
          content:
            application/json:
              schema:
                type: object
                properties: 
                  message: 
                    type: string
                example:
                  message: "'steps' muss ein Integer sein"




  /advanced:
    post:
      tags:
      - "advanced"
      summary: "Advanced Transformation"
      description: "Parameter für die Transformation"

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Advanced"
      responses:
        200:
          description: "Berechnung erfolgreich"
          content:
            application/json:
              schema:  
                type: "object"
                properties: 
                  meta:
                    $ref: "#/components/schemas/Meta"
                  result:
                    $ref: "#/components/schemas/GeoJSON"
        400:
          description: "Fehlerhafte Parameterübergabe"

  /datetime:
    post:
      tags:
      - "datetime"
      summary: "Datumstransformation"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                category:
                  type: "string"
                  enum: 
                  - mjd
                  - bdat
                  - gpsweek
                  - ydoy
                  - yr
                  description: >
                    Mögliche Parameter: 
                      * `bdat` - "YYYY-MM-DD::Date"
                      * `mjd` - "Float::Modified Julian Date"
                      * `gpsweek` - "WWWW.D::GPSWeek and Day of Week"
                      * `ydoy` - "YYYY.DDD::Year and Day of Year"
                      * `yr` - "YYYY.FF::Fractional Year (YYYY.50 = Half of year)"
                value:
                  type: "string"
              required:
                - category
                - value
              example:
                category: "yr"
                value: "2019.25" 
      responses:
        200:
          description: "Everything ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DateTime"
        400:
          description: "Fehlerhafte Parameterübergabe"
        
  /cadastre/determination:
    post:
      tags:
      - "cadastre"
      summary: "Datumstransformation"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CadastreDetermination"
      responses:
        200: 
          description: "Bestimmung der Transformationsparameter erfolgreich."
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  s02:
                    type: "number"
                    format: "float"
                    description: "Sigma Null"
                  params:
                    $ref: '#/components/schemas/CadastreParameter'
                  sigmas:
                    $ref: '#/components/schemas/SigmasCadastreParameter'
                  residuals:
                    type: "array"
                    items: 
                      type: "object"
                      properties:
                        name:
                          type: "string"
                          description: "Punktnummer"
                        east:
                          type: "number"
                          format: "float"
                          description: "Residual in Ost-Richtung [m]"
                        north:
                          type: "number"
                          format: "float"
                          description: "Residual in Nord-Richtung [m]"
                        height:
                          type: "number"
                          format: "float"
                          description: "Residual in der Höhen-Komponente [m]"
                    example:
                    - name: 83015-0041A1
                      east: 0.052
                      north: -0.033
                      height: -0.782
                    - name: 83015-0055A2
                      east: 0.028
                      north: 0.006
                      height: -0.739
                    - name: 83015-0118A1
                      east: -0.028
                      north: 0.011
                      height: -0.757
                    - name: 83015-0119A1
                      east: -0.017
                      north: 0.016
                      height: -0.776
                    - name: 83015-0122E1
                      east: -0.01
                      north: 0.025
                      height: -0.756
                    - name: 83015-0123E1
                      east: -0.025
                      north: -0.024
                      height: -0.787                
                  improvements:
                    type: "array"
                    items: 
                      type: "object"
                      properties:
                        name:
                          type: "string"
                          description: "Punktnummer"
                        east:
                          type: "number"
                          format: "float"
                          description: "Normierte Verbesserung in Ost-Richtung []"
                        north:
                          type: "number"
                          format: "float"
                          description: "Normierte Verbesserung in Nord-Richtung []"
                    example:          
                    - name: 83015-0041A1
                      east: 3.2
                      north: -2
                    - name: 83015-0055A2
                      east: 2.1
                      north: 0.4
                    - name: 83015-0118A1
                      east: -1.9
                      north: 0.7
                    - name: 83015-0119A1
                      east: -0.9
                      north: 0.9
                    - name: 83015-0122E1
                      east: -0.6
                      north: 1.5
                    - name: 83015-0123E1
                      east: -1.4
                      north: -1.3
                  height_shift:
                    type: "number"
                    format: "float"
                    description: "!!! Future Implementation !!!"
                    example: 0.0
                  meridian: 
                    $ref: '#/components/schemas/Meridian'

  /cadastre/transformation:
    post:
      tags:
      - "cadastre"
      summary: "Datumstransformation"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:   
                etrs_points:
                  $ref: "#/components/schemas/GeoJSON"
                helmert_parameter:
                  $ref: '#/components/schemas/CadastreParameter'
                height_shift:
                    type: "number"
                    format: "float"
                    description: "!!! Future Implementation !!!"
                    example: 0.0
                meridian: 
                  $ref: '#/components/schemas/Meridian'
    
                use_height_grid:
                  type: "boolean"
      responses:
        200:
          description: "Transformationsergebnis der Neupunkte."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  meta: 
                    $ref: '#/components/schemas/Meta'
                  result:
                    $ref: '#/components/schemas/GeoJSON'
                
  /cadastre/report:
    post:
      tags:
      - "cadastre"
      summary: "PDF-Report der Parameterbestimmung und Transformation"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:   
                report_key_determination:
                  type: "string"
                  description: "Der Report-Key steht im Meta-Teil des Responses von /cadastre/determination"
                report_key_transformation:
                  type: "string"
                  description: "Der Report-Key steht im Meta-Teil des Responses von /cadastre/transformation"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:    
                  pdf:
                    type: "string"
                    format: "binary"
                    description: "pdf im binary-Format"

  /helmert/2d/determination:
    post:
      tags:
      - "helmert"
      summary: "Bestimmung von 2d-Transformationsparameter"
      description: "Von den übergebenen GeoJSON-Objekten werden für die Transformation nur Point-Features verwendet. Alle Anderen Geometrien werden ignoriert. Die Passpunkte werden anhand der Punktnamen identifiziert. Bitte geben Sie mindestens 2 Punkte für die Bestimmung ein."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:   
                source_points:
                  $ref: '#/components/schemas/GeoJSON'
                target_points:
                  $ref: '#/components/schemas/GeoJSON'
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  meta: 
                    $ref: '#/components/schemas/Meta'
                  result:
                    type: "object"
                    properties:
                      params:
                        $ref: '#/components/schemas/2dParameter'
                      s02_apriori:
                        type: "number"
                        format: "float"
                        description: "Apriori-Sigma"
                      s02_posteriori:
                        type: "number"
                        format: "float"
                        description: "APosteriori-Sigma"
                      sigmas:
                        $ref: '#/components/schemas/2dParameter'
  
  /helmert/2d/transformation:
    post:
      tags:
      - "helmert"
      summary: "2d-Helmert Transformation"
      description: "Anwendung der ebenen Helmert-Transformation mit eigenen Transformationsparametern."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:   
                points:
                  $ref: '#/components/schemas/GeoJSON'
                de:
                  type: "number"
                  format: "float"
                  description: "Verschiebung nach Osten [m]"
                dn:
                  type: "number"
                  format: "float"
                  description: "Verschiebung nach Norden [m]"
                m:
                  type: "number"
                  format: "float"
                  description: "Maßstab []"
                r:
                  type: "number"
                  format: "float"
                  description: "Rotationswinkel []"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  meta: 
                    $ref: '#/components/schemas/Meta'
                  result: 
                    type: "object"
                    properties:
                      points:
                        $ref: '#/components/schemas/GeoJSON'
            
  /helmert/3d/determination:
    post:
      tags:
      - "helmert"
      summary: "Bestimmung von 3d-Transformationsparameter"
      description: "Von den übergebenen GeoJSON-Objekten werden für die Transformation nur Point-Features verwendet. Alle Anderen Geometrien werden ignoriert. Die Passpunkte werden anhand der Punktnamen identifiziert. Bitte geben Sie mindestens 3 Punkte für die Bestimmung ein."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:   
                source_points:
                  $ref: '#/components/schemas/GeoJSON'
                target_points:
                  $ref: '#/components/schemas/GeoJSON'
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  meta: 
                    $ref: '#/components/schemas/Meta'
                  result:
                    type: "object"
                    properties:
                      params:
                        $ref: '#/components/schemas/3dParameter'
                      s02_apriori:
                        type: "number"
                        format: "float"
                        description: "Apriori-Sigma"
                      s02_posteriori:
                        type: "number"
                        format: "float"
                        description: "APosteriori-Sigma"
                      sigmas:
                        $ref: '#/components/schemas/3dParameter'
                    
  /helmert/3d/transformation:
    post:
      tags:
      - "helmert"
      summary: "3d-Helmert-Transformation"
      description: "Anwendung der räumlichen Helmert-Transformation mit eigenen Transformationsparametern."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:   
                points:
                  $ref: '#/components/schemas/GeoJSON'
                d_x:
                  type: "number"
                  format: "float"
                  description: "Translation entlang der X-Achse [Einheit der Passpunkte]"
                d_y:
                  type: "number"
                  format: "float"
                  description: "Translation entlang der Y-Achse [Einheit der Passpunkte]"
                d_z:
                  type: "number"
                  format: "float"
                  description: "Translation entlang der Z-Achse [Einheit der Passpunkte]"
                m:
                  type: "number"
                  format: "float"
                  description: "Maßstab []"
                r_x:
                  type: "number"
                  format: "float"
                  description: "Rotation um die X-Achse []"
                r_y:
                  type: "number"
                  format: "float"
                  description: "Rotation um die Y-Achse []"
                r_z:
                  type: "number"
                  format: "float"
                  description: "Rotation um die Z-Achse []"
              
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  meta: 
                    $ref: '#/components/schemas/Meta'
                  result: 
                    type: "object"
                    properties:
                      points:
                        $ref: '#/components/schemas/GeoJSON'
                    
  /austrian:
    post:
      tags:
      - "austrian"
      summary: "Transformation zwischen ETRS und MGI"
      description: "GRID-Transformation zwischen dem europäischen Koordinatensystem ETRS89 und dem System der österreichischen Landesvermessung MGI mit GIS-Grid und Höhengrid. Beispiel ETRS89 λφh ellipsoidisch nach M34 Gebrauchshöhe mit GIS GRID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:   
                geojson:
                  $ref: '#/components/schemas/GeoJSON'
                source_crs:
                  $ref: '#/components/schemas/AustrianCRS'
                source_height_system:
                  $ref: '#/components/schemas/AustrianHeights'
                target_crs:
                  $ref: '#/components/schemas/AustrianCRS'
                target_height_system:
                  $ref: '#/components/schemas/AustrianHeights'
                transformation_method:
                  type: "string"
                  enum:
                  - BEV::2001
                  - BEV::2002
                  description: >
                    Mögliche Parameter: 
                      * `BEV::2001` - "BEV 7 Parameter"
                      * `BEV::2002` - "GIS Grid"
      responses:
        200:
          description: "Transformation erfolgreich"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  meta:
                    $ref: '#/components/schemas/Meta'
                  result:
                    type: "object"
                    properties: 
                      points:
                        $ref: '#/components/schemas/GeoJSON'
                  



security:
  - BasicAuth: []


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    singleHeight:
      type: object
      properties:
        height: 
          type: number
          format: "float"
      example: 
        height: 296.9

    point_list:
      type: array
      minItems: 2
      items: 
        type: array
        minItems: 2
        maxItems: 2
        items:
          type: number
          format: float
      example: [[15.1, 48.2], [15.2, 48.1]]


    heightProfileRequest:
      type: object
      properties:
        point_list:
          $ref: "#/components/schemas/point_list"
        steps:
          type: integer
          maximum: 500
          example: 123
        precise:
          type: boolean
          default: false
          example: false
      required:
        - point_list
        - steps
    

    heightProfile:
      type: object
      properties:
        stats:
          type: object
          properties:
            highestPoint:
              type: number
              format: float
            lowestPoint:
              type: number
              format: float
            heightDiffMinMax:
              type: number
              format: float
            heightDiffStartEnd:
              type: number
              format: float
            sumUps:
              type: number
              format: float
            sumDowns:
              type: number
              format: float
            dist:
              type: number
              format: float
          example:
            highestPoint: 1946.89
            lowestPoint: 633.36
            heightDiffMinMax: 1313.53
            heightDifStartEnd: -792.17
            sumUps: 7003.76
            sumDowns: -7795.76
            dist: 87540.5
        point_list:
          $ref: "#/components/schemas/point_list"
        bbox:
          type: array
          minItems: 4
          maxItems: 4
          items: 
            type: number
            format: float
          example: [15.1, 48.2, 15.2, 48.4]
        heights:
          type: array
          minItems: 2
          items: 
            type: number
            format: float
          example: [1031.4, 1045.6]



    Coordinates:
      type: array
      maxItems: 3
      minItems: 2
      items:
        type: number
      example:
        [1,2,3]
    
    Velocities:
      type: array
      maxItems: 3
      minItems: 2
      items:
        type: number
      example:
        [0.1,0.2,0.3]
    
    Point:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id2
      properties:
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        velocities:
          $ref: '#/components/schemas/Velocities'
      
    LineString:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id3
      properties:
        coordinates:
          type: array
          items:
            $ref: '#/components/schemas/Coordinates'
        velocities:
          type: array
          items:
            $ref: '#/components/schemas/Velocities'
  
    Polygon:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id4
      properties:
        coordinates:
          type: array
          items:
            type: array
            items:
              $ref: '#/components/schemas/Coordinates'
    
    MultiPoint:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id5
      properties:
        coordinates:
          type: array
          items:
            $ref: '#/components/schemas/Coordinates'
          
    MultiLineString:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id6
      properties:
        coordinates:
          type: array
          items:
            type: array
            items:
              $ref: '#/components/schemas/Coordinates'
        
    MultiPolygon:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id6
      properties:
        coordinates:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                $ref: '#/components/schemas/Coordinates'
        
    GeometryCollection:
      type: object
      description: GeoJSon geometry collection
      required:
       - type
       - geometries
      externalDocs:
        url: http://geojson.org/geojson-spec.html#geometrycollection
      properties:
        type:
          type: string
          enum:
          - GeometryCollection
        geometries:
            type: array
            items:
              $ref: '#/components/schemas/GeoJSON'
    
    DateTime:
      type: "object"
      properties:
        error: 
          type: "string"
          description: "Gibt ggfalls eine Fehlermeldung aus."
        ut:
          type: "integer"
          description: "?!?!?!?!?!?"
        year:
          type: "integer"
          description: "Jahreszahl als Integer"
        doy:
          type: "integer"
          description: "Tag des Jahres. Ganzzahlig. Beginnend mit 1"
        month:
          type: "integer"
          description: "Monat"
        day:
          type: "integer"
          description: "Tag des Monats"
        jd:
          type: "number"
          format: "float"
          description: "Julianisches Datum"
        mjd:
          type: "number"
          format: "float"
          description: "Modifiziertes Julianisches Datum"        
        gpsweek:
          type: "integer"
          description: "GpsWeek. Anzahl der Wochen seit 6.1.1980 00:00 UTC "
        dow:
          type: "integer"
          description: "Day of Week. Tag der Woche beginnt mit Sonntag als 0"
        sow:
          type: "integer"
          description: "Second of Week. Beginnt Sonntag 00:00 UTC mit 0"
        hour:
          type: "integer"
          description: "Stunde des Tages"        
        minute:
          type: "integer"
          description: "Minute der angefangenen Stunde"
        second:
          type: "integer"
          description: "Sekunde der angefangenen Minute"
        iso:
          type: "string"
          format: "date-time"
          description: "ISO Time Format. Siehe https://tools.ietf.org/html/rfc3339#section-5.6"        
        isoblank:
          type: "string"
          description: "Wie `iso`, allerdings mit ' ' als Zwischenräume"
        bdat:
          type: "string"
          format: "date"
          description: "Bürgerliches Datum"
        yr:
          type: "number"
          format: "float"
          description: "Jahr mit 2 Nachkommastellen. Dieses Format wird für die `epoch` beim Model `CRS` verwendet."
        ydoy:
          type: "string"
          description: "Year and day of year. YYYY.DOY Jahr mit drei Nachkommastellen zwischen 001 und 366"   
      example:
        error: null
        ut: 7.5
        year: 2019
        month: 4
        day: 2
        jd: 2458575.8125
        mjd: 58575.3125
        gpsweek: '2047.2'
        dow: 2
        sow: 199800
        hour: 7
        minute: 30
        second: 0
        tag0: 2458483.5
        doy: 92
        iso: '2019-04-02T07:30:00'
        isoblank: 2019 04 02 07 30 00
        bdat: '2019-04-02'
        yr: 2019.25
        ydoy: '2019.092'
        
    Meridian:
      type: "string"
      enum: 
      - GK_AUTO
      - GK_M28
      - GK_M31
      - GK_M34
      description: >
        Mögliche Parameter: 
          * `GK_AUTO` - "Automatic definition of Reference Meridian"
          * `GK_M28` - "MGI/GK Meridian M28 (West)"
          * `GK_M31` - "MGI/GK Meridian M21 (Central)"
          * `GK_M34` - "MGI/GK Meridian M34 (East)"
          
    AustrianCRS:
      type: "string"
      enum:
      - mgi_xyz
      - mgi_lph
      - mgi_lcc
      - mgi_gk28
      - mgi_gk31
      - mgi_gk34
      - etrs89_xyz
      - etrs89_lph
      - etrs89_lcc
      - etrs89_utm32n
      - etrs89_utm33n
      description: >
        Mögliche Parameter: 
          * `mgi_xyz` - "MGI X, Y, Z"
          * `mgi_lph` - "MGI Lam, Phi, H"
          * `mgi_lcc` - "MGI Lambert Austria"
          * `mgi_gk28` - "MGI GK M28"
          * `mgi_gk31` - "MGI GK M31"
          * `mgi_gk34` - "MGI GK M34"
          * `etrs89_xyz` - "ETRS89 X, Y, Z"
          * `etrs89_lph` - "ETRS89 Lam, Phi, H"
          * `etrs89_lcc` - "ETRS89 Lambert Austria"
          * `etrs89_utm32n` - "ETRS89 UTM 32N"
          * `etrs89_utm33n` - "ETRS89 UTM 33N"  

    AustrianHeights:
      type: "string"
      enum: 
      - ortho
      - ellps
      - usage
      description: >
        Mögliche Parameter: 
          * `ortho` - "Orthometrische Höhe"
          * `ellps` - "Ellipsoidische Höhe"
          * `usage` - "Gebrauchshöhe"
                    
    2dParameter:
      type: "object"
      description: "Die mit den Passpunkten bestimmten Parameter"
      properties:
        translation_east:
          type: "number"
          format: "float"
          description: "Translation nach Osten [Einheit der Passpunkte]"
        translation_north:
          type: "number"
          format: "float"
          description: "Translation nach Norden [Einheit der Passpunkte]"
        scale:
          type: "number"
          format: "float"
          description: "Maßstab []"
        rotation:
          type: "number"
          format: "float"
          description: "Rotationswinkel []"
      example:
        translation_east: 24.5119
        translation_north: 55.6914
        scale: 1.00000241
        rotation: 2.568e-05
        
    3dParameter:
      type: "object"
      description: "Die mit den Passpunkten bestimmten Parameter"
      properties:
        translation_x:
          type: "number"
          format: "float"
          description: "Translation entlang der X-Achse [Einheit der Passpunkte]"
        translation_y:
          type: "number"
          format: "float"
          description: "Translation entlang der Y-Achse [Einheit der Passpunkte]"
        translation_z:
          type: "number"
          format: "float"
          description: "Translation entlang der Z-Achse [Einheit der Passpunkte]"
        scale:
          type: "number"
          format: "float"
          description: "Maßstab []"
        rotation_x:
          type: "number"
          format: "float"
          description: "Rotation um die X-Achse []"
        rotation_y:
          type: "number"
          format: "float"
          description: "Rotation um die Y-Achse []"
        rotation_z:
          type: "number"
          format: "float"
          description: "Rotation um die Z-Achse []"
      example:
        translation_x: 45.8768
        translation_y: 4.8599
        translation_z: 59.8545
        rotation_x: -0.27320539
        rotation_y: 0.10319804
        rotation_z: -0.26286031
        scale: 0.39126504
        


    CRS:
      type: "object"
      properties:
        frame:
          type: "string"
        epoch:
          type: "number"
          format: "float"
          default: 2002.56
          description: "Epoch of CRS [YYYY.DDD]"
        ellipsoid:
          type: "string"
          description: "Required if 'projection' is set"
        prime_meridian:
          type: "string"
          default: "Greenwhich"
        projection:
          type: "string"
      required:
        - frame
        #- epoch
      example:
        frame: '301'
        epoch: 2002.56
        ellipsoid: 'EPSG::7004'
        prime_meridian: 'EPSG::8909'
        projection: 'BEV::10034'
        heightsystem: usage  
 
 
    GeoJSON:
      type: object
      description: GeoJSON File
      #discriminator: type
      required:
        - type
      externalDocs:
        url: http://geojson.org/geojson-spec.html#geometry-objects
      properties:
        type:
          type: "string"
          example: "FeatureCollection"
        crs:
          type: "object"
          properties:
            type:
              type: "string"
            crs:
              $ref: '#/components/schemas/CRS'
          description: "Das Coordinate Reference System muss nicht übergeben werden. Wird es trotzdem übergeben, wird es ignoriert. Aber: Es wird als Ergebnis ausgegeben und ist notwendig um das Koordinatenbezugssystem zu beschreiben."
        features:
          type: array
          items:
            type: "object"
            properties:
              type:
                type: "string"
                enum: 
                - Point
                - MultiPoint
                - LineString
                - MultiLineString
                - Polygon
                - MultyPolygon
                - GeometryCollection
                #description: >
                #  Mögliche Parameter: 
                #    * `bdat` - "YYYY-MM-DD::Date"
                #    * `mjd` - "Float::Modified Julian Date"
                #    * `gpsweek` - "WWWW.D::GPSWeek and Day of Week"
                #    * `ydoy` - "YYYY.DDD::Year and Day of Year"
                #    * `yr` - "YYYY.FF::Fractional Year (YYYY.50 = Half of year)"
              coordinates:
                type: "array"
                items:
                  type: "number"
                  format: "float"
                
              velocities:
                type: "array"
                items:
                  type: "number"
                  format: "float"
                  
      example:
        type: FeatureCollection
        crs:
          type: BEV
          name: ''
          properties:
            frame: '302'
            ellipsoid: 'EPSG::7030'
            epoch: '2019.55'
            prime_meridian: 'EPSG::8901'
            projection: ''
            height_system: ''
        features:
          - type: Feature
            geometry:
              type: Point
              coordinates: [4082885.131, 1193419.671, 4737392.091]
              velocities: [0.10, 0.02, 0.03]
            properties:
              name: 10-40A1
          - type: Feature
            geometry:
              type: Point
              coordinates: [4082858.119, 1193441.636, 4737388.976]
              velocities: [0.04,-0.001,0.0]
            properties:
              name: 10-40A2
    
  
    Advanced:
      type: "object"
      properties:
        source_crs:
          $ref: "#/components/schemas/CRS"
        target_crs:
          $ref: "#/components/schemas/CRS"
        geojson:
          $ref: "#/components/schemas/GeoJSON"
      required:
        - source_crs
        - target_crs
        - geojson
      
  
    Meta:
      type: "object"
      properties: 
        request_url: 
          type: "string"
          description: "Die aufgerufene URl"
        user: 
          type: "string"
          description: "Username"
        token:
          type: "string"
          description: "Ihr API KEY"
        datetime:
          type: "string"
          format: "date-time"
          description: "Zeitpunkt der Berechnung."
        points: 
          type: "integer"
          format: "int64"
          description: "Anzahl der Transformierten Punkte"
        report_key:
          type: "string"
          description: "Gibt es nur im Kataster-Mode. Wird benötigt um das pdf-Transformationsprotokoll zu erzeugen."
      example:
        request_url: '/api/v3.0/advanced/'
        user: 'anonymous'
        token: '0000000000000000000000000000000000000000'
        datetime: '2019-07-19 13:29:07.925109+00:00'
        points: 21
        report_key: 'a50330ccac4011e98144005056a64e39'
  
    CadastreDetermination:
      type: "object"
      properties:
        meridian:
          $ref: '#/components/schemas/Meridian'
        fix_scale:
          type: "boolean"
          default: "false"
          description: "Setzt den Maßstab=1. Die Innere Geometrie wird erhalten."
        etrs_points:
          $ref: '#/components/schemas/GeoJSON' 
        mgi_points:
          $ref: '#/components/schemas/GeoJSON'
      example:
        meridian: GK_AUTO
        fix_scale: false
        mgi_points:
          type: FeatureCollection
          features:
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - -89288.81
                  - 267365.42
                  - 601.44
              properties:
                name: 83015-0041A1
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - -88309.11
                  - 267667.56
                  - 652.95
              properties:
                name: 83015-0055A2
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - -88892.5
                  - 266831.07
                  - 663.53
              properties:
                name: 83015-0118A1
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - -88830.98
                  - 267337.46
                  - 619.41
              properties:
                name: 83015-0119A1
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - -88929.43
                  - 267733.82
                  - 614.79
              properties:
                name: 83015-0122E1
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - -88968.22
                  - 267437.31
                  - 607.7
              properties:
                name: 83015-0123E1
        etrs_points:
          type: FeatureCollection
          features:
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - 4217534.793
                  - 907752.004
                  - 4682895.595
              properties:
                name: 83015-0041A1
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - 4217134.846
                  - 908663.169
                  - 4683147.703
              properties:
                name: 83015-0055A2
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - 4217871.591
                  - 908238.154
                  - 4682584.843
              properties:
                name: 83015-0118A1
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - 4217465.299
                  - 908205.674
                  - 4682894.753
              properties:
                name: 83015-0119A1
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - 4217199.508
                  - 908041.549
                  - 4683157.886
              properties:
                name: 83015-0122E1
            - type: Feature
              geometry:
                type: Point
                coordinates:
                  - 4217416.312
                  - 908053.186
                  - 4682952.06
              properties:
                name: 83015-0123E1      
   
    CadastreParameter:
      type: "object"
      description: "Die mit den Passpunkten bestimmten Parameter"
      properties:
        ce:
          type: "number"
          format: "float"
          description: "Rotationszentrum Rechtswert [m]"
        cn:
          type: "number"
          format: "float"
          description: "Rotationszentrum Hochwert [m]"
        de:
          type: "number"
          format: "float"
          description: "Verschiebung nach Osten [m]"
        dn:
          type: "number"
          format: "float"
          description: "Verschiebung nach Norden [m]"
        m:
          type: "number"
          format: "float"
          description: "Maßstab []"
        r:
          type: "number"
          format: "float"
          description: "Rotationswinkel []"
      example:
        ce: -88869.4483
        cn: 267395.304
        de: -0.3934
        dn: 0.136
        m: 1.00000211
        r: -5.469e-05
  
    SigmasCadastreParameter:
      type: "object"
      description: "Genauigkeiten der mit den Passpunkten bestimmten Parameter"
      properties:
        ce:
          type: "number"
          format: "float"
          description: "Genauigkeit des Rotationszentrum Rechtswert [m]"
        cn:
          type: "number"
          format: "float"
          description: "Genauigkeit des Rotationszentrum Hochwert [m]"
        de:
          type: "number"
          format: "float"
          description: "Genauigkeit des Verschiebung nach Osten [m]"
        dn:
          type: "number"
          format: "float"
          description: "Genauigkeit des Verschiebung nach Norden [m]"
        m:
          type: "number"
          format: "float"
          description: "Genauigkeit des Maßstab []"
        r:
          type: "number"
          format: "float"
          description: "Genauigkeit des Rotationswinkel []"
      example:
        ce: null
        cn: null
        de: 0.0129
        dn: 0.0129
        m: 3.126e-05
        r: 3.126e-05

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
